name: Build coconutOS images

on:
  workflow_dispatch:
    inputs:
      datecode:
        description: "Override datecode for images"
        required: false
        type: string
      mirror:
        description: "Mirror to use"
        default: "https://repo-ci.voidlinux.org/current"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container:
      image: 'ghcr.io/void-linux/void-linux:20230204RC01-full-x86_64'
      options: --privileged
      volumes:
        - /dev:/dev
      env:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'
        DATECODE: "${{ inputs.datecode }}"
        LIVE_ARCHS: "x86_64"
        LIVE_FLAVORS: "base"
        REPO: "${{ inputs.mirror }}"

    steps:
      - name: Prepare container
        shell: sh
        run: |
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|https://repo-default.voidlinux.org/current|'"$REPO"'|g' /etc/xbps.d/*-repository-*.conf
          xbps-install -Syu || xbps-install -yu xbps
          xbps-install -yu
          xbps-install -yu bash make git kmod xz lzo qemu-user-static outils dosfstools e2fsprogs

      - name: Clone and checkout
        uses: actions/checkout@v3
      
      - name: Prepare environment
        run: |
          echo "DATECODE=$(date -u "+%Y%m%d")" >> $GITHUB_ENV
          echo "MKLIVE_REV=${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Build live ISOs
        run: |
          if ! [[ "$LIVE_ARCHS" = "none" || "$LIVE_FLAVORS" = "none" ]]; then
              make live-iso-all{-print,} \
                  LIVE_ARCHS="$LIVE_ARCHS" LIVE_FLAVORS="$LIVE_FLAVORS" \
                  SUDO= REPOSITORY="$REPO" DATECODE=$DATECODE
          else
              echo "Nothing to do..."
          fi
          
      - name: Prepare artifacts for upload
        run: |
          make dist checksum DATECODE=$DATECODE
          
      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: coconutOS-live-${{ env.DATECODE }}
          path: distdir-${{ env.DATECODE }}/*
          if-no-files-found: error
